package com.example.qpid.config;

import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.context.annotation.Configuration;

// Create QPidJmsProperties based on spring.qpid-jms properties
@Configuration
@ConfigurationProperties(prefix = "spring.qpid-jms")
public class QPidJmsProperties {

  /**
   * URL of the AMQP broker. Auto-generated by default.
   */
  private String remoteUrl;

  /**
   * Login user of the AMQP broker.
   */
  private String username;

  /**
   * Login password of the AMQP broker.
   */
  private String password;

  public String getRemoteUrl() {
    return remoteUrl;
  }

  public void setRemoteUrl(String remoteUrl) {
    this.remoteUrl = remoteUrl;
  }

  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }

  public String getPassword() {
    return password;
  }

  public void setPassword(String password) {
    this.password = password;
  }
}
