version: '3.6'
services:
  php-app:
    image: php:apache
    container_name: app
    ports:
      - '80:80'
    restart: unless-stopped
# This container will start after this list of dependable containers
    depends_on:
      - app-db
      - app-redis
    networks:
      - internet
      - localnet

  app-db:
    image: postgres
    container_name: app-postgres
    restart: unless-stopped
    environment:
      - 'POSTGRES_PASSWORD=mysecretpassword'
    networks:
      - localnet

  app-redis:
    image: redis
    container_name: app-redis
    restart: unless-stopped
    networks:
      - localnet

networks:
  internet:
    name: internet
    driver: bridge
  localnet:
    name: localnet
    driver: bridge
