version: '3.5'
services:
  web-server:
    image: nginx:stable
    container_name: mynginx
    volumes:
      - '/mnt/e/Programming/Java projects/Tutorials/Docker/Docker-Compose - RomNero/Files/HTML/:/var/www/html'
      - '/mnt/e/Programming/Java projects/Tutorials/Docker/Docker-Compose - RomNero/Files/IMG:/var/www/pictures'
      - 'nginx-config:/var/www/config'
    environment:
      - 'NGINX_HOST=web.alex.md'
      - 'NGINX_PORT=80'
    ports:
      - '80:80'
      - '443:443'
    restart: unless-stopped
volumes:
  nginx-config:
networks:
  default:
    driver: bridge
    name: webnet
